package com.paybridge.audit;

public enum AuditAction {
    PAYMENT_APPROVED,
    PAYMENT_FULL_REVERSAL_RECORDED,
    PAYMENT_PARTIAL_REVERSAL_RECORDED,
    STRIPE_WEBHOOK_RECEIVED,
    STRIPE_WEBHOOK_PROCESSED,
    STRIPE_WEBHOOK_DUPLICATE,
    STRIPE_WEBHOOK_REJECTED
}
